version: '3.8'

services:
  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: corrosion_platform_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: corrosion_platform
      MYSQL_USER: corrosion_user
      MYSQL_PASSWORD: corrosion_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - corrosion_network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: corrosion_platform_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - corrosion_network

  # Django后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: corrosion_platform_backend
    restart: always
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=corrosion_platform
      - DB_USER=corrosion_user
      - DB_PASSWORD=corrosion_pass
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - corrosion_network

  # Vue前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: corrosion_platform_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - corrosion_network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: corrosion_platform_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - backend_static:/var/www/static
      - backend_media:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - corrosion_network

volumes:
  mysql_data:
  redis_data:
  backend_media:
  backend_static:

networks:
  corrosion_network:
    driver: bridge
