# Generated by Django 4.2.7 on 2025-10-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '信息分类',
                'verbose_name_plural': '信息分类',
                'db_table': 'info_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('supply', '供应信息'), ('demand', '需求信息'), ('recruitment', '招聘信息'), ('tender', '招标信息'), ('technology', '技术文章'), ('news', '行业资讯'), ('other', '其他')], max_length=20, verbose_name='信息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('contact_info', models.TextField(blank=True, verbose_name='联系信息')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期至')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='info_plaza.infocategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '信息发布',
                'verbose_name_plural': '信息发布',
                'db_table': 'info_posts',
                'ordering': ['-is_top', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='标签颜色')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '信息标签',
                'verbose_name_plural': '信息标签',
                'db_table': 'info_tags',
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InfoViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='info_plaza.infopost', verbose_name='信息发布')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_view_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信息浏览日志',
                'verbose_name_plural': '信息浏览日志',
                'db_table': 'info_view_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfoPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_post_images/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='info_plaza.infopost', verbose_name='信息发布')),
            ],
            options={
                'verbose_name': '信息发布图片',
                'verbose_name_plural': '信息发布图片',
                'db_table': 'info_post_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='info_plaza.infocomment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='info_plaza.infopost', verbose_name='信息发布')),
            ],
            options={
                'verbose_name': '信息评论',
                'verbose_name_plural': '信息评论',
                'db_table': 'info_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='info_plaza.infopost', verbose_name='信息发布')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信息点赞',
                'verbose_name_plural': '信息点赞',
                'db_table': 'info_likes',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InfoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='info_plaza.infopost', verbose_name='信息发布')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信息收藏',
                'verbose_name_plural': '信息收藏',
                'db_table': 'info_favorites',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
